#+TITLE: Danioche Linux set-up and customization
#+OPTIONS: toc:2 num:3 H:4 ^:nil pri:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css"/>
#+OPTIONS: html-style:nil
#+AUTHOR: @danioche
#+DATE: <2020-06-05 vie>

* About
  
  This document it's aimed to help to configure *mostly any* /Ubuntu/
  (and recently /Fedora/) distro to working-distro with the most
  common set-up that I'm used to.  The distro-dependency is because
  this includes some package-managers-dependency, I include on the
  codes some scripting in shell for invoquing the installation.  Main
  tools, corporate and productivity tools; and of course with the
  look&feel from a preconfigured repo.

  Following literate documentation approach, inspiring post:
  http://cachestocaches.com/2018/6/org-literate-programming/

  #+ATTR_TEXTINFO: :author @danioche
  #+BEGIN_QUOTE
  
    All the shell code here comes without any warranty, AT ALL,
    execute it (or not) at your own risk.  I assume that you
    understand the code, you can modif, use it, post it, or whatever,
    at your own risk :)

  #+END_QUOTE

  Also, document format for exporting in HTML is from [[https://gongzhitaao.org/orgcss/][gongzhitaao]],
  clean and nice CSS, very useful. Thanks!

  Bellow the latest commit mesage:

  #+begin_src sh :results output

    echo "Showing last 5 changes on the project:"
    echo "-----------------------------------------"
    git log -5 --pretty=%B --date=relative

  #+end_src

  #+RESULTS:
  #+begin_example
  Showing last 5 changes on the project:
  -----------------------------------------
  Weather scripts and Xmobar review, Added bottom bar in Xmonad cfg

  Small changes on format

  Spacemacs config moved to dotfiles and small text improvements

  .emacs improved - auto-install of packages added

  Updating text and contents on main org file

  #+end_example


** Check your space

   You may want to check your disk space befor continue on this
   customization. Some software (if you decide) will be installed in
   your system so if you are runing with limmited amout on space this
   could be useful:

   #+begin_src sh :results output

     df -H /

   #+end_src

#+RESULTS:
: S.ficheros     Tamaño Usados  Disp Uso% Montado en
: /dev/mmcblk0p3    30G    16G   14G  54% /

I try to avoid bloated linux distros, but the most recent distros comes with at least ~ 15Gb, and, really, is quite a lot for a linux system.
I love minimal installations ( I still remember the installations of Slackware that I made in my beloved Compaq Armada with 1Gb W95 + Slackware, nice uh? ).

** Improvements [2/4]
   In this section I will record some taks and TODOs for future versions
*** DONE <2021-01-17 dom> Export configuration

    Configuration using gongzhintaao CSS that is enough for now, maybe we
    could add future improvements.

*** DONE Backup Tools
     - <2021-12-29 mié> New code blocks on [[Tools][Tools section]] to patch
       configurations from current user to this project and viceversa.
*** TODO Auto-install scripts
*** TODO Improve README on the project
* This project

  The structure that I want is a private repository (If you are
  reading this is because you colaborate or I decided that the project
  is mature enough to make it public) that will have all the scripts
  needed to config the new distro.

  Ansible and playbooks are also options to take into account but,
  because the distro is configured for using as
  "regular-manager/coder-user" I don't need any specific "server-side"
  conditions. So I decided more the literate-programming approach to
  fullfil my customization requirements.

  Obviously what is inside is this main ORG file, that is a literate
  document; so once you installed Emacs and Spacemacs you will be able
  to execute the configurations as you wish.

  Summarizing, the step-0 is to have git (if you are reading this
  document sequentialy you may have needed before).

  #+begin_src sh

    git version

  #+end_src

  #+RESULTS:
  : git version 2.31.1

  If Ctr+C Ctr+C does not works showing you the following message:
  "Evaluation of this sh code block is disabled" then you may have a
  problem on configuration here is a trick:

   - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

  This configuration project also is assuming that the target linux
  installation uses 'apt' package manager. Because I also have som
  systema on Fedora that uses 'dnf' package manager you may also find
  some code to install most used packages.

  #+BEGIN_QUOTE

   This kind of errors may happen if you play too much with Emacs or
   Org package, I came up with this problem in Spacemacs. But in DOOM
   Emacs worked as expected from the first time. Anyway, if you have
   further problems let me know!

  #+END_QUOTE

** Installing git

   Welcome to 2021, it's time to do it! :). 

   The following command may be not fully working from this documentation, but you can
   copy-paste to install it.

   #+begin_src sh

   sudo apt-get install git

   #+end_src

   #+RESULTS:

   If your Linux is brand new you may need to add your .rsa or create
   a new one for the nes OS, follow the instructions here:

   - https://github.com/settings/keys

   Help info: 
   - https://help.github.com/articles/generating-a-gpg-key/

/*Obviously*: If you don't have emacs installed and configured you will not be able to execute here the code above, so you may want to visit next section./

* Tools
** EMACS

   The main tool (a part from git :) for taking the most of this
   document is EMACS, you want to have it installed.

   - https://www.gnu.org/software/emacs/

   I'm using EMACS since 2017 for Instant Project Management, TimeSheet
   management, GTD and other cool stuff like to support this
   document. Emacs is mainly the key-factor for many features and tricks
   that I'm doing in my everyday workflow stream.

   #+begin_src sh

   sudo apt-get install emacs

   #+end_src

   And the flavour that I --like-- liked most is the *spacemacs*
   https://www.spacemacs.org/

   The following lines will move your current personal folder from
   emacs to back-up (just in case), and then will clone the latest
   stable repository for espacemacs.

   #+begin_src sh

   mv ~/.emacs.d ~/.emacs.d.old
   git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

   #+end_src

   With version 25 (current version is 27 by the time of writing) of
   EMACS in Ubuntu 18 i found an issue, related to signature update,
   if you find yourself again with this error you can solve it
   following the instructions:

   You can check your linux version with the following code:

   #+begin_src sh

   uname -a

   #+end_src
   #+RESULTS:
   : Linux localhost.localdomain 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

   Documentation on "signature" fails after spacemacs install:

   - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

**** My stored spacemacs configuration

     Here is the most stable configuration on *.spacemacs* file inside
     the dotfiles folder.

     #+begin_src sh

     cp ~/.spacemacs ~/.spacemacs.bk
     cp ./dotfiles/spacemacs/.spacemacs ~/.spacemacs

     #+end_src

***** DONE Move spacemacs configuration to dotfile folder
      <2021-05-30 dom> Fixed. In fact I was using dotfile folder for
      storing .emacs


*** DOOM EMACS
    
    I'm trying new things, after getting bored of watching DOOM Emacs videos, I just tought... let's try it!

    Starting at: <2020-12-18 vie> ... we will see...


    #+begin_src sh

    git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install

    #+end_src

    After several months using it I found Doom Emacs too big for my use, I
    mainly use: ORG, HUGO and some few things, so I preferred to have more
    minimalistic configuration.

*** EMACS my own Config

    Finally I found myself wanted something less bloated, more
    light. May be I will lose some functionallities but at least I
    will configure the ones that I use.

    At this moment I'm just configuring .emacs file, not dotorg
    config, for now...

    #+begin_src sh
    
    mv -v ~/.emacs ~/.emacs.bk
    cp -v ./dotfiles/emacs/.emacs ~/.emacs

    #+end_src

    This config uses some "art" 

    #+begin_src sh

    cp -vr ./art ~/Imágenes/art 

    #+end_src

** GIMP

   The graphical editor!

   #+begin_src sh

   sudo apt-get install gimp

   #+end_src

** Dotfiles directories tools: Check, Patch/Backup, Restore

   This is a /"diff"/ tool to check if the current configuration on your
   system is updated with the stored configuration on this project.

   *some credits* 
   Diff and Patch commands are based on this post:
   https://www.shellhacks.com/create-patch-diff-command-linux/

   The stuff:
   
   #+name: mainChecks 
   #+begin_src sh :results output

     echo "Checking local Xmonad config vs. this project config: "
     diff -rN --brief ./dotfiles/xmonad/.xmonad/ ~/.xmonad > checks.xmonad
     changes=`cat checks.xmonad | wc -l`
     echo ">>>Found $changes differences for Xmonad"

     echo "Checking local Emacs config vs. this project config: "
     diff --brief ./dotfiles/emacs/.emacs ~/.emacs > checks.emacs
     changes=`cat checks.emacs | wc -l`
     echo ">>>Found $changes differences for .emacs"

     echo "Checking local Xmobar config vs. this project config: "
     diff --brief ./dotfiles/xmobar/.xmobarrc ~/.xmobarrc > checks.xmobarrc
     changes=`cat checks.xmobarrc | wc -l`
     echo ">>>Found $changes differences for .xmobarrc"


   #+end_src  
   #+RESULTS: mainChecks
   : Checking local Xmonad config vs. this project config: 
   : >>>Found 14 differences for Xmonad
   : Checking local Emacs config vs. this project config: 
   : >>>Found 0 differences for .emacs
   : Checking local Xmobar config vs. this project config: 
   : >>>Found 0 differences for .xmobarrc

   With the following code block will generate patches for *UPDATING
   this CONFIG stored on this project* with the ones modified on your
   system, in other words *IT DOES a backup of your dotfiles inside
   project dotfiles*.
   
   #+NAME: PatchingDirectories
   #+BEGIN_SRC sh :results output

     echo "Building Patches/Backups if needed..."
     diff  -ruN ./dotfiles/xmonad/.xmonad ~/.xmonad > patch.xmonad
     patchXmonad=`cat patch.xmonad | wc -l`
     if [ $patchXmonad -gt 0 ]; then
	 echo ">>> Patch for Xmonad ready: patch.xmonad " 
     fi

     diff  -u ./dotfiles/xmobar/.xmobarrc ~/.xmobarrc > patch.xmobarrc
     patchXmobar=`cat patch.xmobarrc | wc -l`
     if [ $patchXmobar -gt 0 ]; then
	 echo ">>> Patch for Xmobarrc ready: patch.xmobarrc " 
     fi

     diff  -u ./dotfiles/emacs/.emacs ~/.emacs > patch.emacs
     patchEmacs=`cat patch.emacs | wc -l`
     if [ $patchEmacs -gt 0 ]; then
	 echo ">>> Patch for Emacs ready: patch.emacs " 
     fi

     echo "Fin."

   #+END_SRC
   #+RESULTS: PatchingDirectories
   : Building Patches/Backups if needed...
   : >>> Patch for Xmonad ready: patch.xmonad 
   : >>> Patch for Xmobarrc ready: patch.xmobarrc 
   : >>> Patch for Emacs ready: patch.emacs 
   : Fin.

   With the following code you can *restore your config files* from the ones on this project.

   #+NAME: RestoreDirectories
   #+BEGIN_SRC sh :results output

     echo "Building Restoring Patches if needed..."
     diff  -ruN ~/.xmonad ./dotfiles/xmonad/.xmonad > restore.xmonad
     patchXmonad=`cat backup.xmonad | wc -l`
     if [ $patchXmonad -gt 0 ]; then
	 echo ">>> Backup patch for Xmonad ready: restore.xmonad " 
     fi

     diff  -u ~/.xmobarrc ./dotfiles/xmobar/.xmobarrc > restore.xmobarrc
     patchXmobar=`cat backup.xmobarrc | wc -l`
     if [ $patchXmobar -gt 0 ]; then
	 echo ">>> Backup patch for Xmobarrc ready: restore.xmobarrc " 
     fi

     diff  -u ~/.emacs ./dotfiles/emacs/.emacs > restore.emacs
     patchEmacs=`cat backup.emacs | wc -l`
     if [ $patchEmacs -gt 0 ]; then
	 echo ">>> Backup patch for Emacs ready: restore.emacs " 
     fi

     echo "Fin."

   #+END_SRC

   #+RESULTS: RestoreDirectories
   : Building Restoring Patches if needed...
   : Fin.

   How to apply the Patches.

   Now this will up to you, the following code block is just an
   example no parametrization has been made because I do not want you
   blaming this beatiful org file because of your mistake :D.

   This will be the commands:

   #+name: PatchFileSample
   #+begin_src sh :results output

     # do the patch
     patch OriginalFile < PatchFile
     # This will save your xmobarrc file to this project
     patch dotfiles/xmobar/.xmobarrc < patch.xmobarrc
     # This will UPDATE your xmobarrc file with the one in this project
     patch ~/.xmobarrc < restore.xmobarrc

     # undo the patch
     patch -R OriginalFile < PatchFile

   #+end_src

   #+name: PatchDirSample
   #+begin_src sh :results output

     #do the patch -- This will apply the changes on the same directory
     #structure when patch was created
     patch -p0 < PatchFile

     #undo
     patch -R -p0 < PatchFile

   #+end_src

   Clean this mess

   #+name: CleanPatches
   #+begin_src sh :results output

     rm checks.*
     rm patch.*
     rm restore.*

   #+end_src 

   #+RESULTS: CleanPatches
      
* Terminal
** system
   This section is in which i recommend some system tools if not installed.
*** HTop                                                  :system:monitoring:

    Mostly (AFAIK) top should be included, but htop is more powerfull
    and fancy from terminal

    #+begin_src sh :results output

    sudo dnf install htop

    #+end_src

    #+RESULTS:

*** Bashtop                                               :system:monitoring:
    
    Very nice application to be installed, all the linux youtubers use
    it, so you should so, shouldn't? B)

    #+BEGIN_SRC sh
    
    sudo dnf install bashtop 
    
    #+END_SRC

** Powerline

   Powerline is a very usefull aplication when you use git, I
   recommend to install it. More info at:

   For ubuntu

   #+begin_src sh

   sudo apt-get install fonts-powerline powerline

   #+end_src

   For DNF package manager

   #+begin_src sh

   sudo dnf install powerline

   #+end_src

   #+RESULTS:

   After installation you should include into your .bashrc the
   initialization of the powerline, for doing this first check your
   installation path
   
   #+begin_src sh

   whereis powerline

   #+end_src
   #+RESULTS:
   : powerline: /usr/bin/powerline /usr/share/powerline /usr/share/man/man1/powerline.1.gz

   You should have a script to be included on your .bashrc: 

   #+begin_src sh

   ls -l /usr/share/powerline/bash/powerline.sh

   #+end_src
   #+RESULTS:
   : -rw-r--r--. 1 root root 4183 mar 15 10:31 /usr/share/powerline/bash/powerline.sh

   If th above is working then you can addit executing the following code:

   #+begin_src sh

   cp ~/.bashrc ~/.bashrc.bk
   echo "# Powerline" >> ~/.bashrc
   echo "export PATH=$PATH:$HOME/Library/Python/2.7/bin" >> ~/.bashrc
   echo "powerline-daemon -q" >> ~/.bashrc
   echo "POWERLINE_BASH_CONTINUATION=1" >>  ~/.bashrc
   echo "POWERLINE_BASH_SELECT=1" >> ~/.bashrc
   echo ". /usr/share/powerline/bash/powerline.sh" >> ~/.bashrc
   echo "Done! :)"

   #+end_src

   #+RESULTS:
   : Done! :)

   Check your Python version BTW

   #+begin_src sh :results output

   python -V

   #+end_src

   #+RESULTS:
   : Python 3.9.1

   Now you want to add to the powerline the git theme on Shell, this is very easy!
   I added in the repo my config file for this (very standard BTW).

   #+begin_src sh

   cp /usr/share/powerline/config_files/config.json ./config.json.bk
   cp ./powerline-conf/config.json /usr/share/powerline/config_files/

   #+end_src

   #+RESULTS:

   You will need to open a new terminal after changing the
   *config.json* file.

   More info: https://devpro.media/install-powerline-ubuntu/#edit-your-powerline-configuration

*** TODO To improve colors in powerline-git config to show changes on directory are pending

** Some fun
*** Pokemon on your terminal

   I love the pokemon say addon for terminal, is a litle bit of fun on
   your term:

   - https://github.com/possatti/pokemonsay

   #+begin_src sh

   sudo apt-get install fortune cowsay

   #+end_src

   For Fedora, there is an slight difference

   #+begin_src sh

   sudo dnf install fortune-mod
   sudo dnf install cowsay

   #+end_src

   #+RESULTS:

   Some test that you have preinstalled what is needed:

   #+begin_src sh :results output

   fortune | cowsay

   #+end_src

   #+RESULTS:
   :  ___________________________
   : < Life is not for everyone. >
   :  ---------------------------
   :         \   ^__^
   :          \  (oo)\_______
   :             (__)\       )\/\
   :                 ||----w |
   :                 ||     ||

   #+begin_src sh :results output

   cd ~/
   git clone http://github.com/possatti/pokemonsay
   cd pokemonsay
   ./install.sh

   #+end_src

   #+RESULTS:
   : The files were installed to '/home/danioche/.pokemonsay/'.
   : A 'pokemonsay' script was created in '/home/danioche/bin/'.
   : A uninstall script was created in '/home/danioche/.pokemonsay/'.
   : It may be necessary to logout and login back again in order to have the 'pokemonsay' available in your path.

   Now you want to add it to your .bashrc file to get some cool wellcome everytime you enter to your terminal.

   #+begin_src sh :results output

   cp ~/.bashrc ~/.bashrc.before.pokesay
   echo "# Pokemon say add-on" >> ~/.bashrc
   echo "fortune | ~/bin/pokemonsay " >> ~/.bashrc
   diff ~/.bashrc ~/.bashrc.before.pokesay

   #+end_src

   #+RESULTS:

*** Ascii art

    Sometimes is nice to beutify your terminal with some ascii art.

    #+begin_src sh
    
    sudo dnf install figlet
    
    #+end_src 

    #+RESULTS:

    You can test it!

    #+begin_src sh 

    fig hello

    #+end_src

    #+RESULTS:

** Weather info
   
   I like sailing and weather conditions are something to look at,
   I've tested several programs on terminal that I found useful, here are.

*** Using inxi

    Inxi is a Command line system information for console and IRC,
    this allows you to have many information about the system and also
    Weather information, visit it's manual page. 

    This is not an standard tool so you will need to install it using
    your package manager.


   #+begin_src sh :results output
   
   inxi -W Alicante,Spain
   
   #+end_src

   #+RESULTS:
   : 12Weather:   12Report 12temperature 16 C (61 F) 12conditions Overcast clouds 
   :            12Locale 12current time dom 05 dic 2021 19:57:38 12Source WeatherBit.io 

*** Using wttr.in

   Having *curl* installed in your system this is a good tool with
   propper information and lightweight due the fact that is not needed
   any installation.

   #+begin_src sh :results output

   curl wttr.in/LEAL?lang=es 

   #+end_src

   #+RESULTS:
   #+begin_example
   El tiempo en: LEAL

     [38;5;226m   \  /[0m       Parcialmente nublado
     [38;5;226m _ /""[38;5;250m.-.    [0m [38;5;118m+15[0m([38;5;118m13[0m) °C[0m     
     [38;5;226m   \_[38;5;250m(   ).  [0m [1m→[0m [38;5;214m22[0m km/h[0m      
     [38;5;226m   /[38;5;250m(___(__) [0m 10 km[0m          
		   0.0 mm[0m         
							  ┌─────────────┐                                                       
   ┌──────────────────────────────┬───────────────────────┤  dom 05 dic ├───────────────────────┬──────────────────────────────┐
   │            Mañana            │           Mediodía    └──────┬──────┘      Tarde            │             Noche            │
   ├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
   │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Despejado      │ [38;5;226m    \   /    [0m Despejado      │
   │ [38;5;226m     .-.     [0m [38;5;082m+12[0m([38;5;046m9[0m) °C[0m      │ [38;5;226m     .-.     [0m [38;5;154m18[0m °C[0m          │ [38;5;226m     .-.     [0m [38;5;118m+15[0m([38;5;082m12[0m) °C[0m     │ [38;5;226m     .-.     [0m [38;5;082m+12[0m([38;5;046m9[0m) °C[0m      │
   │ [38;5;226m  ― (   ) ―  [0m [1m→[0m [38;5;202m29[0m-[38;5;196m41[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m→[0m [38;5;196m39[0m-[38;5;196m45[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↘[0m [38;5;196m43[0m-[38;5;196m49[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↘[0m [38;5;196m32[0m-[38;5;196m41[0m km/h[0m   │
   │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │
   │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │
   └──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
							  ┌─────────────┐                                                       
   ┌──────────────────────────────┬───────────────────────┤  lun 06 dic ├───────────────────────┬──────────────────────────────┐
   │            Mañana            │           Mediodía    └──────┬──────┘      Tarde            │             Noche            │
   ├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
   │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Despejado      │ [38;5;226m   \  /[0m       Parcialmente n…│
   │ [38;5;226m     .-.     [0m [38;5;082m+11[0m([38;5;046m8[0m) °C[0m      │ [38;5;226m     .-.     [0m [38;5;154m17[0m °C[0m          │ [38;5;226m     .-.     [0m [38;5;118m15[0m °C[0m          │ [38;5;226m _ /""[38;5;250m.-.    [0m [38;5;118m+13[0m([38;5;082m12[0m) °C[0m     │
   │ [38;5;226m  ― (   ) ―  [0m [1m↘[0m [38;5;202m30[0m-[38;5;196m41[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↘[0m [38;5;196m38[0m-[38;5;196m44[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↘[0m [38;5;208m26[0m-[38;5;196m33[0m km/h[0m   │ [38;5;226m   \_[38;5;250m(   ).  [0m [1m↘[0m [38;5;220m17[0m-[38;5;202m28[0m km/h[0m   │
   │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m   /[38;5;250m(___(__) [0m 10 km[0m          │
   │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │               0.0 mm | 0%[0m    │
   └──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
							  ┌─────────────┐                                                       
   ┌──────────────────────────────┬───────────────────────┤  mar 07 dic ├───────────────────────┬──────────────────────────────┐
   │            Mañana            │           Mediodía    └──────┬──────┘      Tarde            │             Noche            │
   ├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
   │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Soleado        │ [38;5;226m    \   /    [0m Despejado      │ [38;5;226m    \   /    [0m Despejado      │
   │ [38;5;226m     .-.     [0m [38;5;118m+13[0m([38;5;082m12[0m) °C[0m     │ [38;5;226m     .-.     [0m [38;5;190m19[0m °C[0m          │ [38;5;226m     .-.     [0m [38;5;154m18[0m °C[0m          │ [38;5;226m     .-.     [0m [38;5;154m16[0m °C[0m          │
   │ [38;5;226m  ― (   ) ―  [0m [1m→[0m [38;5;226m14[0m-[38;5;208m26[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↗[0m [38;5;226m14[0m-[38;5;220m16[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m↗[0m [38;5;226m15[0m-[38;5;220m19[0m km/h[0m   │ [38;5;226m  ― (   ) ―  [0m [1m→[0m [38;5;226m15[0m-[38;5;208m27[0m km/h[0m   │
   │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │ [38;5;226m     `-’     [0m 10 km[0m          │
   │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │ [38;5;226m    /   \    [0m 0.0 mm | 0%[0m    │
   └──────────────────────────────┴──────────────────────────────┴──────────────────────────────┴──────────────────────────────┘
   Ubicación: Aeropuerto de Alicante-Elche, N-338, El Altet, Elx / Elche, el Baix Vinalopó, Alacant / Alicante, Comunitat Valenciana, 03008, España [38.2844177,-0.565752908110604]

   Sigue a [46m[30m@igor_chubin[0m para enterarte de las novedades de wttr.in
   #+end_example

   It's complete information but at the same time is way too much if
   you just want the minimum information.

*** Using OpenWeatherMap API

    One solution is made it yourself by using the OpenWeatherMap API,
    you can register (I did, no confirmation link sent me back...)

    Once I will get the confirmation link maybe I could use this:

   #+begin_src sh :results output

   curl api.openweathermap.org/data/2.5/weather?q=Alicante&appid=

   #+end_src

   #+RESULTS:

*** Using weather-util
    
    Nice utility from one-developer, nice to read the README of this
    tool, the "Why" section is heart-warmming. Love is the answer.
    
    You should visit and download the latest tar at 
    > http://fungi.yuggoth.org/weather/src/

    #+begin_src sh :results output
    
    weather -a LEAL 
  
    #+end_src

    #+RESULTS:
    : Searching via station...
    : [caching result Alicante / El Altet, Spain]
    : Current conditions at Alicante / El Altet, Spain (LEAL) 38-17N 000-33W 31M
    : Last updated Dec 05, 2021 - 04:30 PM EST / 2021.12.05 2130 UTC
    :    Temperature: 53 F (12 C)
    :    Relative Humidity: 54%
    :    Wind: from the WNW (290 degrees) at 14 MPH (12 KT) (direction variable)
    :    Sky conditions: mostly clear
    : (no current alerts for this zone)

*** Using Puertos del Estado
    
    For maritime forecast in Spain I use Puertos del Estado web page

    #+begin_src sh :results output

     curl -X POST -d 'point=2079100&name=Alicante' https://bancodatos.puertos.es/TablaAccesoSimplificado/util/get_wanadata.php | html2text

    #+end_src

    #+RESULTS:
    #+begin_example
      ,* Las direcciones indican dirección de procedencia
      ,* Valores obtenidos del punto de malla situado en lat: **38.3330** y lon: **-0.4170**

    ---  

    Alicante | Viento | Mar Total | Mar de Viento | Mar de Fondo 1 | Mar de Fondo
    2  
    ---|---|---|---|---|---  
    Fecha | Horiz. | Vv (m/s) | Dir | Hs (m) | Dir | Tp (s) | Tz (s) | Hs (m) |
    Dir | Hs (m) | Dir | Tz (s) | Hs (m) | Dir | Tz (s)  
    2021-12-05 13:00:00 | 0 | 10.78 | 290-WNW | 0.57 | 259-W | 3.19 | 2.41 | 0.52
    | 268-W | 0.16 | 206-SSW | 3.05 | 0.09 | 192-SSW | 6.15  
    2021-12-05 14:00:00 | 1 | 10.36 | 312-NW | 0.50 | 269-W | 2.90 | 2.35 | 0.44 |
    284-WNW | 0.13 | 223-SW | 2.40 | 0.13 | 226-SW | 3.75  
    2021-12-05 15:00:00 | 2 | 10.38 | 314-NW | 0.49 | 278-W | 2.90 | 2.35 | 0.44 |
    290-WNW | 0.14 | 232-SW | 3.20 | 0.14 | 193-SSW | 15.42  
    2021-12-05 16:00:00 | 3 | 8.56 | 311-NW | 0.43 | 281-W | 2.63 | 2.37 | 0.39 |
    293-WNW | 0.09 | 192-SSW | 10.15 | 0.09 | 192-SSW | 5.69  
    2021-12-05 17:00:00 | 4 | 6.07 | 313-NW | 0.33 | 276-W | 11.01 | 2.39 | 0.26 |
    298-WNW | 0.10 | 192-SSW | 10.15 | 0.04 | 46-NE | 10.07  
    2021-12-05 18:00:00 | 5 | 4.56 | 303-WNW | 0.24 | 250-WSW | 11.01 | 2.42 |
    0.16 | 296-WNW | 0.10 | 192-SSW | 10.24 | 0.05 | 47-NE | 9.85  
    2021-12-05 19:00:00 | 6 | 3.25 | 324-NW | 0.21 | 209-SSW | 11.01 | 2.57 | 0.05
    | 319-NW | 0.11 | 192-SSW | 10.41 | 0.05 | 47-NE | 9.76  
    2021-12-05 20:00:00 | 7 | 4.84 | 295-WNW | 0.23 | 208-SSW | 11.01 | 2.16 |
    0.14 | 285-WNW | 0.11 | 191-S | 10.88 | 0.05 | 50-NE | 9.95  
    2021-12-05 21:00:00 | 8 | 4.71 | 294-WNW | 0.30 | 230-SW | 11.01 | 1.88 | 0.22
    | 281-W | 0.12 | 190-S | 10.91 | 0.11 | 194-SSW | 6.00  
    2021-12-05 22:00:00 | 9 | 4.66 | 280-W | 0.33 | 231-SW | 11.01 | 2.05 | 0.23 |
    274-W | 0.12 | 190-S | 10.92 | 0.09 | 45-NE | 9.40  
    2021-12-05 23:00:00 | 10 | 3.68 | 280-W | 0.31 | 137-SE | 11.01 | 2.61 | 0.14
    | 275-W | 0.14 | 46-NE | 8.54 | 0.08 | 57-ENE | 11.60  
    2021-12-06 00:00:00 | 11 | 5.19 | 257-WSW | 0.32 | 119-ESE | 11.01 | 2.51 |
    0.18 | 254-WSW | 0.16 | 60-ENE | 11.60 | 0.10 | 42-NE | 8.80  
    2021-12-06 01:00:00 | 12 | 6.66 | 275-W | 0.39 | 222-SW | 11.01 | 2.17 | 0.28
    | 254-WSW | 0.19 | 55-NE | 10.54 | 0.11 | 190-S | 10.96  
    2021-12-06 02:00:00 | 13 | 7.67 | 286-WNW | 0.39 | 248-WSW | 11.01 | 2.41 |
    0.28 | 263-W | 0.17 | 49-NE | 10.10 | 0.09 | 72-ENE | 12.91  
    2021-12-06 03:00:00 | 14 | 8.35 | 287-WNW | 0.42 | 256-WSW | 11.01 | 2.38 |
    0.32 | 265-W | 0.15 | 59-ENE | 11.18 | 0.10 | 41-NE | 9.01  
    2021-12-06 04:00:00 | 15 | 8.08 | 304-NW | 0.41 | 259-W | 11.01 | 2.41 | 0.28
    | 279-W | 0.13 | 58-ENE | 10.96 | 0.10 | 41-NE | 8.92  
    2021-12-06 05:00:00 | 16 | 8.79 | 312-NW | 0.41 | 268-W | 11.01 | 2.30 | 0.30
    | 288-WNW | 0.12 | 45-NE | 9.08 | 0.08 | 64-ENE | 11.72  
    2021-12-06 06:00:00 | 17 | 7.09 | 316-NW | 0.39 | 278-W | 2.39 | 2.39 | 0.29 |
    298-WNW | 0.13 | 196-SSW | 5.62 | 0.13 | 49-NE | 9.99  
    2021-12-06 07:00:00 | 18 | 6.79 | 320-NW | 0.38 | 292-WNW | 2.39 | 2.45 | 0.29
    | 303-WNW | 0.10 | 46-NE | 8.59 | 0.10 | 64-ENE | 12.68  
    2021-12-06 08:00:00 | 19 | 9.10 | 313-NW | 0.43 | 312-NW | 11.01 | 2.45 | 0.35
    | 304-NW | 0.12 | 56-NE | 10.96 | 0.08 | 71-ENE | 12.79  
    2021-12-06 09:00:00 | 20 | 9.85 | 310-NW | 0.46 | 327-NNW | 11.01 | 2.48 |
    0.37 | 305-NW | 0.20 | 56-NE | 10.61 | 0.10 | 198-SSW | 5.75  
    2021-12-06 10:00:00 | 21 | 8.48 | 307-NW | 0.46 | 334-NNW | 11.01 | 2.58 |
    0.36 | 300-WNW | 0.23 | 56-NE | 10.54 | 0.08 | 198-SSW | 5.72  
    2021-12-06 11:00:00 | 22 | 7.01 | 323-NW | 0.43 | 358-N | 11.01 | 2.74 | 0.29
    | 307-NW | 0.23 | 54-NE | 10.25 | 0.15 | 55-NE | 3.89  
    2021-12-06 12:00:00 | 23 | 5.63 | 321-NW | 0.36 | 17-NNE | 11.01 | 2.81 | 0.22
    | 309-NW | 0.22 | 53-NE | 9.99 | 0.13 | 53-NE | 3.50  
    2021-12-06 13:00:00 | 24 | 4.94 | 319-NW | 0.32 | 23-NNE | 10.01 | 2.61 | 0.19
    | 308-NW | 0.18 | 48-NE | 9.21 | 0.11 | 63-ENE | 11.64  
    2021-12-06 14:00:00 | 25 | 5.46 | 314-NW | 0.34 | 356-N | 10.01 | 2.14 | 0.25
    | 303-WNW | 0.16 | 47-NE | 9.03 | 0.10 | 63-ENE | 11.73  
    2021-12-06 15:00:00 | 26 | 5.60 | 308-NW | 0.33 | 341-NNW | 10.01 | 2.19 |
    0.25 | 301-WNW | 0.15 | 47-NE | 8.71 | 0.10 | 64-ENE | 11.93  
    2021-12-06 16:00:00 | 27 | 6.00 | 306-NW | 0.33 | 329-NNW | 10.01 | 2.22 |
    0.26 | 297-WNW | 0.13 | 47-NE | 7.85 | 0.10 | 65-ENE | 12.27  
    2021-12-06 17:00:00 | 28 | 4.74 | 283-WNW | 0.30 | 337-NNW | 10.01 | 2.37 |
    0.22 | 286-WNW | 0.12 | 46-NE | 8.59 | 0.09 | 59-ENE | 11.85  
    2021-12-06 18:00:00 | 29 | 3.53 | 272-W | 0.27 | 27-NNE | 12.11 | 2.60 | 0.12
    | 274-W | 0.16 | 61-ENE | 11.91 | 0.10 | 44-NE | 8.07  
    2021-12-06 19:00:00 | 30 | 4.38 | 287-WNW | 0.27 | 50-NE | 12.11 | 3.00 | 0.12
    | 280-W | 0.23 | 57-ENE | 9.66 | 0.02 | 41-NE | 2.88  
    2021-12-06 20:00:00 | 31 | 6.01 | 264-W | 0.31 | 52-NE | 12.11 | 2.71 | 0.16 |
    262-W | 0.25 | 57-ENE | 9.58 | 0.02 | 204-SSW | 5.18  
    2021-12-06 21:00:00 | 32 | 5.50 | 260-W | 0.38 | 44-NE | 12.11 | 2.39 | 0.26 |
    248-WSW | 0.26 | 57-ENE | 9.78 | 0.03 | 195-SSW | 6.07  
    2021-12-06 22:00:00 | 33 | 10.29 | 243-WSW | 0.51 | 230-SW | 12.11 | 2.44 |
    0.43 | 235-SW | 0.26 | 56-NE | 9.89 | 0.05 | 191-S | 6.75  
    2021-12-06 23:00:00 | 34 | 8.84 | 256-WSW | 0.59 | 221-SW | 12.11 | 2.71 |
    0.47 | 236-SW | 0.25 | 56-NE | 10.83 | 0.20 | 190-S | 5.43  
    2021-12-07 00:00:00 | 35 | 7.48 | 252-WSW | 0.61 | 206-SSW | 11.01 | 2.93 |
    0.42 | 236-SW | 0.24 | 56-NE | 10.80 | 0.23 | 190-S | 6.05  
    2021-12-07 01:00:00 | 36 | 4.74 | 266-W | 0.57 | 193-SSW | 12.11 | 3.22 | 0.23
    | 254-WSW | 0.25 | 191-S | 6.09 | 0.25 | 56-NE | 11.04  
    2021-12-07 02:00:00 | 37 | 4.59 | 282-WNW | 0.52 | 189-S | 12.11 | 3.29 | 0.15
    | 260-W | 0.24 | 55-NE | 10.62 | 0.22 | 192-SSW | 6.05  
    2021-12-07 03:00:00 | 38 | 5.08 | 307-NW | 0.48 | 188-S | 12.11 | 3.29 | 0.08
    | 274-W | 0.23 | 55-NE | 10.16 | 0.16 | 193-SSW | 5.56  
    2021-12-07 04:00:00 | 39 | 2.83 | 293-WNW | 0.40 | 179-S | 12.11 | 3.43 |  |
    180-S | 0.22 | 55-NE | 9.96 | 0.17 | 193-SSW | 5.47  
    2021-12-07 05:00:00 | 40 | 3.91 | 303-WNW | 0.33 | 159-SSE | 12.11 | 3.61 |
    0.03 | 295-WNW | 0.26 | 202-SSW | 2.99 | 0.26 | 54-NE | 12.44  
    2021-12-07 06:00:00 | 41 | 1.53 | 303-WNW | 0.29 | 144-SE | 11.01 | 3.80 |  |
    180-S | 0.22 | 200-SSW | 3.01 | 0.22 | 53-NE | 11.46  
    2021-12-07 07:00:00 | 42 | 3.92 | 253-WSW | 0.28 | 157-SSE | 11.01 | 3.71 |
    0.07 | 244-WSW | 0.21 | 196-SSW | 3.66 | 0.21 | 52-NE | 11.83  
    2021-12-07 08:00:00 | 43 | 6.56 | 245-WSW | 0.33 | 192-SSW | 11.01 | 2.53 |
    0.20 | 229-SW | 0.19 | 193-SSW | 4.99 | 0.15 | 51-NE | 9.24  
    2021-12-07 09:00:00 | 44 | 5.53 | 247-WSW | 0.39 | 206-SSW | 6.21 | 2.61 |
    0.26 | 230-SW | 0.19 | 193-SSW | 5.29 | 0.07 | 181-S | 7.13  
    2021-12-07 10:00:00 | 45 | 7.20 | 250-WSW | 0.44 | 209-SSW | 2.63 | 2.57 |
    0.33 | 227-SW | 0.19 | 193-SSW | 5.40 | 0.07 | 181-S | 7.09  
    2021-12-07 11:00:00 | 46 | 6.14 | 251-WSW | 0.43 | 207-SSW | 3.19 | 2.61 |
    0.29 | 232-SW | 0.18 | 194-SSW | 5.39 | 0.06 | 181-S | 7.05  
    2021-12-07 12:00:00 | 47 | 4.69 | 215-SW | 0.37 | 197-SSW | 6.21 | 2.74 | 0.20
    | 217-SW | 0.21 | 191-S | 5.14 | 0.10 | 49-NE | 8.25  
    2021-12-07 13:00:00 | 48 | 5.74 | 209-SSW | 0.37 | 193-SSW | 6.21 | 2.65 |
    0.26 | 203-SSW | 0.24 | 189-S | 5.03 | 0.09 | 48-NE | 7.99  
    2021-12-07 14:00:00 | 49 | 6.80 | 202-SSW | 0.45 | 193-SSW | 6.21 | 2.59 |
    0.38 | 196-SSW | 0.20 | 190-S | 5.72 | 0.09 | 48-NE | 7.77  
    2021-12-07 15:00:00 | 50 | 7.85 | 196-SSW | 0.59 | 189-S | 3.19 | 2.70 | 0.56
    | 190-S | 0.13 | 187-S | 6.36 | 0.08 | 49-NE | 7.61  
    2021-12-07 16:00:00 | 51 | 7.29 | 205-SSW | 0.70 | 186-S | 3.86 | 2.88 | 0.65
    | 190-S | 0.17 | 149-SSE | 4.02 | 0.17 | 188-S | 6.54  
    2021-12-07 17:00:00 | 52 | 6.72 | 214-SW | 0.73 | 186-S | 4.24 | 3.07 | 0.57 |
    197-SSW | 0.34 | 165-SSE | 3.39 | 0.20 | 158-SSE | 4.96  
    2021-12-07 18:00:00 | 53 | 6.16 | 223-SW | 0.74 | 185-S | 4.67 | 3.23 | 0.41 |
    207-SSW | 0.55 | 174-S | 4.00 | 0.26 | 190-S | 4.04  
    2021-12-07 19:00:00 | 54 | 5.77 | 231-SW | 0.74 | 184-S | 4.67 | 3.37 | 0.32 |
    214-SW | 0.54 | 172-S | 4.04 | 0.37 | 193-SSW | 4.08  
    2021-12-07 20:00:00 | 55 | 5.39 | 239-WSW | 0.70 | 184-S | 5.13 | 3.45 | 0.24
    | 222-SW | 0.66 | 181-S | 4.04 | 0.06 | 49-NE | 7.40  
    2021-12-07 21:00:00 | 56 | 5.01 | 247-WSW | 0.65 | 184-S | 5.13 | 3.51 | 0.17
    | 229-SW | 0.62 | 182-S | 4.01 | 0.06 | 49-NE | 7.37  
    2021-12-07 22:00:00 | 57 | 5.42 | 245-WSW | 0.61 | 185-S | 5.13 | 3.46 | 0.19
    | 225-SW | 0.51 | 183-S | 3.87 | 0.25 | 182-S | 6.48  
    2021-12-07 23:00:00 | 58 | 5.83 | 242-WSW | 0.59 | 187-S | 5.13 | 3.32 | 0.22
    | 222-SW | 0.47 | 184-S | 3.90 | 0.47 | 181-S | 13.14  
    2021-12-08 00:00:00 | 59 | 6.25 | 240-WSW | 0.58 | 189-S | 6.83 | 3.16 | 0.26
    | 219-SW | 0.43 | 184-S | 3.95 | 0.43 | 186-S | 10.74  
    2021-12-08 01:00:00 | 60 | 6.34 | 237-WSW | 0.58 | 190-S | 6.83 | 3.09 | 0.29
    | 219-SW | 0.40 | 183-S | 3.94 | 0.40 | 187-S | 10.37  
    2021-12-08 02:00:00 | 61 | 6.42 | 234-SW | 0.57 | 190-S | 6.83 | 3.06 | 0.31 |
    216-SW | 0.38 | 182-S | 3.92 | 0.38 | 188-S | 9.95  
    2021-12-08 03:00:00 | 62 | 6.51 | 231-SW | 0.58 | 190-S | 6.83 | 3.04 | 0.33 |
    214-SW | 0.36 | 181-S | 3.90 | 0.36 | 188-S | 9.39  
    2021-12-08 04:00:00 | 63 | 6.87 | 229-SW | 0.60 | 191-S | 6.83 | 3.01 | 0.37 |
    209-SSW | 0.34 | 188-S | 5.29 | 0.34 | 183-S | 12.96  
    2021-12-08 05:00:00 | 64 | 7.24 | 227-SW | 0.63 | 191-S | 6.83 | 2.97 | 0.42 |
    206-SSW | 0.32 | 189-S | 5.47 | 0.32 | 183-S | 12.04  
    2021-12-08 06:00:00 | 65 | 7.60 | 226-SW | 0.66 | 191-S | 6.83 | 2.93 | 0.48 |
    204-SSW | 0.33 | 188-S | 5.85 | 0.12 | 180-S | 7.63  
    2021-12-08 07:00:00 | 66 | 6.58 | 224-SW | 0.65 | 190-S | 6.83 | 3.00 | 0.43 |
    208-SSW | 0.35 | 188-S | 5.94 | 0.33 | 166-SSE | 3.35  
    2021-12-08 08:00:00 | 67 | 5.56 | 223-SW | 0.64 | 187-S | 6.83 | 3.14 | 0.32 |
    213-SSW | 0.37 | 188-S | 5.99 | 0.35 | 167-SSE | 3.37  
    2021-12-08 09:00:00 | 68 | 4.55 | 221-SW | 0.65 | 184-S | 6.83 | 3.45 | 0.22 |
    216-SW | 0.45 | 177-S | 3.45 | 0.45 | 187-S | 6.97  
    2021-12-08 10:00:00 | 69 | 5.80 | 243-WSW | 0.71 | 184-S | 7.52 | 3.72 | 0.22
    | 220-SW | 0.49 | 184-S | 6.63 | 0.46 | 178-S | 3.52  
    2021-12-08 11:00:00 | 70 | 7.06 | 265-W | 0.79 | 185-S | 7.52 | 3.91 | 0.21 |
    234-SW | 0.76 | 183-S | 4.73 | 0.04 | 49-NE | 6.74  
    2021-12-08 12:00:00 | 71 | 8.31 | 287-WNW | 0.85 | 187-S | 7.52 | 3.79 | 0.25
    | 256-WSW | 0.81 | 183-S | 4.92 | 0.03 | 49-NE | 6.65  

    #+end_example
    
** Fonts

   Source Code Pro is the default font for Emacs, and also is a nice font. Here is how to install it.

   #+begin_src sh :results output

   git clone https://github.com/adobe-fonts/source-code-pro.git ./source-code-pro
   mkdir ~/.fonts
   cp ./source-code-pro/OTF/*.otf ~/.fonts/
   fc-cache -f -v

   #+end_src

   #+RESULTS:
   #+begin_example
   Font directories:
	   /usr/share/fonts
	   /usr/share/X11/fonts/Type1
	   /usr/share/X11/fonts/TTF
	   /usr/local/share/fonts
	   /home/danioche/.local/share/fonts
	   /home/danioche/.fonts
	   /usr/share/fonts/aajohan-comfortaa
	   /usr/share/fonts/adobe-source-code-pro
	   /usr/share/fonts/cantarell
	   /usr/share/fonts/dejavu-sans-fonts
	   /usr/share/fonts/dejavu-sans-mono-fonts
	   /usr/share/fonts/dejavu-serif-fonts
	   /usr/share/fonts/gdouros-symbola
	   /usr/share/fonts/google-carlito-fonts
	   /usr/share/fonts/google-droid-sans-fonts
	   /usr/share/fonts/google-noto
	   /usr/share/fonts/google-noto-cjk
	   /usr/share/fonts/google-noto-emoji
	   /usr/share/fonts/google-noto-vf
	   /usr/share/fonts/ht-caladea-fonts
	   /usr/share/fonts/jomolhari-fonts
	   /usr/share/fonts/julietaula-montserrat
	   /usr/share/fonts/khmeros
	   /usr/share/fonts/liberation-mono
	   /usr/share/fonts/liberation-sans
	   /usr/share/fonts/liberation-serif
	   /usr/share/fonts/lohit-assamese
	   /usr/share/fonts/lohit-bengali
	   /usr/share/fonts/lohit-devanagari
	   /usr/share/fonts/lohit-gujarati
	   /usr/share/fonts/lohit-kannada
	   /usr/share/fonts/lohit-odia
	   /usr/share/fonts/lohit-tamil
	   /usr/share/fonts/lohit-telugu
	   /usr/share/fonts/opensymbol
	   /usr/share/fonts/paktype-naskh-basic
	   /usr/share/fonts/pt-sans-fonts
	   /usr/share/fonts/sil-abyssinica-fonts
	   /usr/share/fonts/sil-mingzat
	   /usr/share/fonts/sil-nuosu
	   /usr/share/fonts/sil-padauk
	   /usr/share/fonts/smc-meera
	   /usr/share/fonts/stix-fonts
	   /usr/share/fonts/thai-scalable
	   /usr/share/fonts/truetype
	   /usr/share/fonts/urw-base35
   /usr/share/fonts: caching, new cache contents: 0 fonts, 40 dirs
   /usr/share/fonts/aajohan-comfortaa: caching, new cache contents: 3 fonts, 0 dirs
   /usr/share/fonts/adobe-source-code-pro: caching, new cache contents: 14 fonts, 0 dirs
   /usr/share/fonts/cantarell: caching, new cache contents: 11 fonts, 0 dirs
   /usr/share/fonts/dejavu-sans-fonts: caching, new cache contents: 9 fonts, 0 dirs
   /usr/share/fonts/dejavu-sans-mono-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/dejavu-serif-fonts: caching, new cache contents: 9 fonts, 0 dirs
   /usr/share/fonts/gdouros-symbola: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/google-carlito-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/google-droid-sans-fonts: caching, new cache contents: 16 fonts, 0 dirs
   /usr/share/fonts/google-noto: caching, new cache contents: 2 fonts, 0 dirs
   /usr/share/fonts/google-noto-cjk: caching, new cache contents: 45 fonts, 0 dirs
   /usr/share/fonts/google-noto-emoji: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/google-noto-vf: caching, new cache contents: 72 fonts, 0 dirs
   /usr/share/fonts/ht-caladea-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/jomolhari-fonts: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/julietaula-montserrat: caching, new cache contents: 18 fonts, 0 dirs
   /usr/share/fonts/khmeros: caching, new cache contents: 3 fonts, 0 dirs
   /usr/share/fonts/liberation-mono: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/liberation-sans: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/liberation-serif: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/lohit-assamese: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-bengali: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-devanagari: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-gujarati: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-kannada: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-odia: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-tamil: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-telugu: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/opensymbol: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/paktype-naskh-basic: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/pt-sans-fonts: caching, new cache contents: 8 fonts, 0 dirs
   /usr/share/fonts/sil-abyssinica-fonts: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-mingzat: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-nuosu: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-padauk: caching, new cache contents: 2 fonts, 0 dirs
   /usr/share/fonts/smc-meera: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/stix-fonts: caching, new cache contents: 5 fonts, 0 dirs
   /usr/share/fonts/thai-scalable: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/truetype: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/urw-base35: caching, new cache contents: 69 fonts, 0 dirs
   /usr/share/X11/fonts/Type1: skipping, no such directory
   /usr/share/X11/fonts/TTF: skipping, no such directory
   /usr/local/share/fonts: skipping, no such directory
   /home/danioche/.local/share/fonts: caching, new cache contents: 6 fonts, 0 dirs
   /home/danioche/.fonts: caching, new cache contents: 0 fonts, 0 dirs
   /usr/share/fonts/aajohan-comfortaa: skipping, looped directory detected
   /usr/share/fonts/adobe-source-code-pro: skipping, looped directory detected
   /usr/share/fonts/cantarell: skipping, looped directory detected
   /usr/share/fonts/dejavu-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/dejavu-sans-mono-fonts: skipping, looped directory detected
   /usr/share/fonts/dejavu-serif-fonts: skipping, looped directory detected
   /usr/share/fonts/gdouros-symbola: skipping, looped directory detected
   /usr/share/fonts/google-carlito-fonts: skipping, looped directory detected
   /usr/share/fonts/google-droid-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/google-noto: skipping, looped directory detected
   /usr/share/fonts/google-noto-cjk: skipping, looped directory detected
   /usr/share/fonts/google-noto-emoji: skipping, looped directory detected
   /usr/share/fonts/google-noto-vf: skipping, looped directory detected
   /usr/share/fonts/ht-caladea-fonts: skipping, looped directory detected
   /usr/share/fonts/jomolhari-fonts: skipping, looped directory detected
   /usr/share/fonts/julietaula-montserrat: skipping, looped directory detected
   /usr/share/fonts/khmeros: skipping, looped directory detected
   /usr/share/fonts/liberation-mono: skipping, looped directory detected
   /usr/share/fonts/liberation-sans: skipping, looped directory detected
   /usr/share/fonts/liberation-serif: skipping, looped directory detected
   /usr/share/fonts/lohit-assamese: skipping, looped directory detected
   /usr/share/fonts/lohit-bengali: skipping, looped directory detected
   /usr/share/fonts/lohit-devanagari: skipping, looped directory detected
   /usr/share/fonts/lohit-gujarati: skipping, looped directory detected
   /usr/share/fonts/lohit-kannada: skipping, looped directory detected
   /usr/share/fonts/lohit-odia: skipping, looped directory detected
   /usr/share/fonts/lohit-tamil: skipping, looped directory detected
   /usr/share/fonts/lohit-telugu: skipping, looped directory detected
   /usr/share/fonts/opensymbol: skipping, looped directory detected
   /usr/share/fonts/paktype-naskh-basic: skipping, looped directory detected
   /usr/share/fonts/pt-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/sil-abyssinica-fonts: skipping, looped directory detected
   /usr/share/fonts/sil-mingzat: skipping, looped directory detected
   /usr/share/fonts/sil-nuosu: skipping, looped directory detected
   /usr/share/fonts/sil-padauk: skipping, looped directory detected
   /usr/share/fonts/smc-meera: skipping, looped directory detected
   /usr/share/fonts/stix-fonts: skipping, looped directory detected
   /usr/share/fonts/thai-scalable: skipping, looped directory detected
   /usr/share/fonts/truetype: skipping, looped directory detected
   /usr/share/fonts/urw-base35: skipping, looped directory detected
   /usr/lib/fontconfig/cache: not cleaning unwritable cache directory
   /home/danioche/.cache/fontconfig: cleaning cache directory
   /home/danioche/.fontconfig: not cleaning non-existent cache directory
   /usr/bin/fc-cache-64: succeeded
   #+end_example

* Productivity
** Code snipets

   This is very useful, you can use skeleton (code in lisp) or you can
   use a module called *yasnippet*, well documented here:

   - https://jaketrent.com/post/code-snippets-spacemacs/ 

   For seleton you can use a configuration layer in spacemacs and code
   your own skeleton in elisp, I made this way some skeleton for IPM
   porpuses.

** Music
*** Lazy Option: Spotify

    Spotify, it's a crap. I'm looking for replacement, but for now...

    #+begin_src sh

    snap install spotify

    #+end_src

*** Improvements and to-do's [0/1]
**** TODO Music from console 
** Presentations
*** reveal-js for Spaceemacs configuration

    A part from LibreOffice suite you may want to have a powerfull tool for presentation. 
    This is for sure reveal.js, you can include it in your org configuration adding in your user layer */dotspacemacs-configuration-layers/*  inside */dotspacemacs/layers/* the following

    #+begin_src lisp
     org
     (org :variables
          org-enable-github-support t
          org-enable-reveal-js-support t)
    #+end_src 

    This configuration is included in the *.spacemacs* file. 

* Blogging

  In this section I will document the use of Hugo and how I adopted
  org-mode with Hugo static web generation.

  Firts of all we need to install Hugo, in Fedora

  #+begin_src sh

  sudo dnf install hugo

  #+end_src

  This is the template that I used as the base for my new blog:
  Anatole Template https://themes.gohugo.io/anatole/

  Adding the template to the current project
  
  I documented the process of the installation and configuration using
  Hugo as static generation in combination with Org-mode.

  Find the post here:
  - https://danioche.github.io/blog

* Destkop Customization
** GDM - Fedora login screen background

   This should be easy but isn't... something quite simple like
   changing the user's login background it is a little big triky.

   For being able to modify the Gnome Desktop Manager login screen
   background you will need to download an specific application.

   Here is what I found in
   https://copr.fedorainfracloud.org/coprs/zirix/gdm-wallpaper/

   #+begin_src sh

   sudo dnf copr enable zirix/gdm-wallpaper
   sudo dnf install gdm-wallpaper
   sudo set-gdm-wallpaper /path/to/image.png

   #+end_src

   And works! I disabled the repository added just in case once is
   installed.

** i3 tiling windows manager

   I'm just trying this, for me is good to have more focus on the
   work, avoiding disrruption and because of this I'm trying i3.

   I tricked some battery problems with the i3status bar, there is a
   .conf file in this repo that you can use:

   #+begin_src sh

   cp ./i3/.i3status.conf ~/

   #+end_src

   Documentation can be found here:
   https://i3wm.org/docs/userguide.html#_default_keybindings

   #+begin_example sh

   ln -s /sys/class/power_supply/axp288_fuel_gauge/ BAT1

   #+end_example

** xmonad tiling windows manager

   I've tried Xmonad and has that minimilistic touch that I love, so
   this is an option to take into consideration, heres is how to
   install.

   The following is for install For Fedora:

   #+begin_src sh

   sudo dnf install xmonad

   #+end_src

   I use xmobar with xmonad, so let's install it:

   #+begin_src sh

   sudo dnf install xmobar

   #+end_src

   For easy the configuration you have .xmonad and .xmobarrc inside
   *dotfiles*

   #+begin_src sh :results output

     printf "Check config and other scripts used by Xmonad and Xmobar:\n\n"
     ls -alR dotfiles/xmo*

   #+end_src

   #+RESULTS:
   #+begin_example
   Check config and other scripts used by Xmonad and Xmobar:

   dotfiles/xmobar:
   total 8
   drwxrwxr-x. 1 danioche danioche  50 dic 29 12:20 .
   drwxrwxr-x. 1 danioche danioche  68 dic 29 12:20 ..
   -rw-rw-r--. 1 danioche danioche 929 dic 29 12:20 .xmobarrc
   -rw-r--r--. 1 danioche danioche 351 dic 29 12:20 .xmobarrcWeather

   dotfiles/xmonad:
   total 0
   drwxrwxr-x. 1 danioche danioche  14 dic 29 12:18 .
   drwxrwxr-x. 1 danioche danioche  68 dic 29 12:20 ..
   drwxrwxr-x. 1 danioche danioche 232 dic 29 12:18 .xmonad

   dotfiles/xmonad/.xmonad:
   total 44
   drwxrwxr-x. 1 danioche danioche   232 dic 29 12:18 .
   drwxrwxr-x. 1 danioche danioche    14 dic 29 12:18 ..
   -rwxrwxr-x. 1 danioche danioche  1189 dic 29 12:18 get-Battery.sh
   -rwxrwxr-x. 1 danioche danioche   267 dic 29 12:18 get-Volume.sh
   -rw-rw-r--. 1 danioche danioche  2040 dic 29 12:18 get-Weather.history
   -rw-r--r--. 1 danioche danioche    52 dic 29 12:18 get-Weather.log
   -rwxrwxr-x. 1 danioche danioche  2500 dic 29 12:18 get-Weather.sh
   -rwxrwxr-x. 1 danioche danioche  1686 dic 29 12:18 get-Weather.sh~
   -rwxrwxr-x. 1 danioche danioche   318 dic 29 12:18 set-Brightness.sh
   -rwxrwxr-x. 1 danioche danioche 12638 dic 29 12:18 xmonad.hs
   #+end_example

   Here is the configuration for xmobar

   #+begin_src sh :results output

     cat dotfiles/.xmobarrc

   #+end_src

   #+RESULTS:
   #+begin_example
   Config { font = "xft:DejaVu Sans Mono:size=10,Font Awesome:size=9"
	  , bgColor = "black"
	  , fgColor = "grey"
	  , position = Top
	  , lowerOnStart = True
	  , commands = [ Run Network "wlp1s0" ["-L","0","-H","15000","--normal","green","--high","red","-S","True","--template","<fc=#04d9ff></fc> <rx>|<tx>"] 10
		       , Run MultiCpu ["-L","3","-H","50","--normal","green","--high","red","-t","<fc=#04d9ff></fc> <bar>"] 10
		       , Run Memory ["-t","<fc=#04d9ff></fc> <usedratio>%"] 10
		       , Run Swap ["-t", "<fc=#04d9ff>S</fc> <usedratio>%"] 10
		       , Run Com "/home/danioche/.xmonad/get-Battery.sh" [] "myBatt" 60
		       , Run WeatherX "LEAL"
			     [ ("clear", "🌣")
			     , ("sunny", "🌣")
			     , ("mostly clear", "🌤")
			     , ("mostly sunny", "🌤")
			     , ("partly sunny", "⛅")
			     , ("fair", "🌑")
			     , ("cloudy","☁")
			     , ("overcast","☁")
			     , ("partly cloudy", "⛅")
			     , ("mostly cloudy", "🌧")
			     , ("considerable cloudiness", "⛈")]
			     ["-t", "<fc=#04d9ff>W</fc> <fn=2><skyConditionS></fn> <tempC>º  <rh>%   <windCardinal>(<windAzimuth>º)  <windKnots>"
			     , "-L","10", "-H", "25", "--normal", "black"
			     , "--high", "lightgoldenrod4", "--low", "darkseagreen4"] 18000
		       , Run Date "%a %b %_d %Y %H:%M:%S" "date" 10
		       ]
	  , sepChar = "%"
	  , alignSep = "}{"
	  , template = "%multicpu% | %memory% %swap% | %wlp1s0% }<fc=#ee9a00> %date%</fc>{ %LEAL% | %myBatt%"
   }
   #+end_example

