#+TITLE: Danioche Linux set-up and customization
#+OPTIONS: toc:2 num:3 H:4 ^:nil pri:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css"/>
#+OPTIONS: html-style:nil
#+AUTHOR: @danioche
#+DATE: <2020-06-05 vie>

* About
  
  This document it's aimed to help to configure *mostly any* /Ubuntu/
  (and recently /Fedora/) distro to working-distro with the most
  common set-up that I'm used to.  The distro-dependency is because
  this includes some package-managers-dependency, I include on the
  codes some scripting in shell for invoquing the installation.  Main
  tools, corporate and productivity tools; and of course with the
  look&feel from a preconfigured repo.

  Following literate documentation approach, inspiring post:
  http://cachestocaches.com/2018/6/org-literate-programming/

  #+ATTR_TEXTINFO: :author @danioche
  #+BEGIN_QUOTE
  
    All the shell code here comes without any warranty, AT ALL,
    execute it (or not) at your own risk.  I assume that you
    understand the code, you can modif, use it, post it, or whatever,
    at your own risk :)

  #+END_QUOTE

  Also, document format for exporting in HTML is from [[https://gongzhitaao.org/orgcss/][gongzhitaao]],
  clean and nice CSS, very useful. Thanks!

  Bellow the latest commit mesage:

  #+begin_src sh :results output

    echo "Showing last 5 changes on the project:"
    echo "-----------------------------------------"
    git log -5 --pretty=%B --date=relative

  #+end_src

  #+RESULTS:
  #+begin_example
  Showing last 5 changes on the project:
  -----------------------------------------
  Spacemacs config moved to dotfiles and small text improvements

  .emacs improved - auto-install of packages added

  Updating text and contents on main org file

  Added .emacs config to dotfiles

  Added Weather info LEAL in xmonad xmobar

  #+end_example


** Check your space

   You may want to check your disk space befor continue on this
   customization. Some software (if you decide) will be installed in
   your system so if you are runing with limmited amout on space this
   could be useful:

   #+begin_src sh :results output

     df -H /

   #+end_src

#+RESULTS:
: S.ficheros     Tamaño Usados  Disp Uso% Montado en
: /dev/mmcblk0p3    30G    16G   14G  54% /

I try to avoid bloated linux distros, but the most recent distros comes with at least ~ 15Gb, and, really, is quite a lot for a linux system.
I love minimal installations ( I still remember the installations of Slackware that I made in my beloved Compaq Armada with 1Gb W95 + Slackware, nice uh? ).

** Improvements

   In this section I will record some taks and TODOs for future versions

*** DONE <2021-01-17 dom> Export configuration

    Configuration using gongzhintaao CSS that is enough for now, maybe we
    could add future improvements.

*** TODO Backup section
*** TODO Auto-install scripts

* This project

  The structure that I want is a private repository (If you are
  reading this is because you colaborate or I decided that the project
  is mature enough to make it public) that will have all the scripts
  needed to config the new distro.

  Ansible and playbooks are also options to take into account but,
  because the distro is configured for using as
  "regular-manager/coder-user" I don't need any specific "server-side"
  conditions. So I decided more the literate-programming approach to
  fullfil my customization requirements.

  Obviously what is inside is this main ORG file, that is a literate
  document; so once you installed Emacs and Spacemacs you will be able
  to execute the configurations as you wish.

  Summarizing, the step-0 is to have git (if you are reading this
  document sequentialy you may have needed before).

  #+begin_src sh

    git version

  #+end_src

  #+RESULTS:
  : git version 2.29.2

  If Ctr+C Ctr+C does not works showing you the following message:
  "Evaluation of this sh code block is disabled" then you may have a
  problem on configuration here is a trick:

   - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

  This configuration project also is assuming that the target linux
  installation uses 'apt' package manager. Because I also have som
  systema on Fedora that uses 'dnf' package manager you may also find
  some code to install most used packages.

  #+BEGIN_QUOTE

   This kind of errors may happen if you play too much with Emacs or
   Org package, I came up with this problem in Spacemacs. But in DOOM
   Emacs worked as expected from the first time. Anyway, if you have
   further problems let me know!

  #+END_QUOTE

** Installing git

   Welcome to 2021, it's time to do it! :). 

   The following command may be not fully working from this documentation, but you can
   copy-paste to install it.

   #+begin_src sh

   sudo apt-get install git

   #+end_src

   #+RESULTS:

   If your Linux is brand new you may need to add your .rsa or create
   a new one for the nes OS, follow the instructions here:

   - https://github.com/settings/keys

   Help info: 
   - https://help.github.com/articles/generating-a-gpg-key/

/*Obviously*: If you don't have emacs installed and configured you will not be able to execute here the code above, so you may want to visit next section./

* Tools
** EMACS

   The main tool (a part from git :) for taking the most of this
   document is EMACS, you want to have it installed.

   - https://www.gnu.org/software/emacs/

   I'm using EMACS since 2017 for Instant Project Management, TimeSheet
   management, GTD and other cool stuff like to support this
   document. Emacs is mainly the key-factor for many features and tricks
   that I'm doing in my everyday workflow stream.

   #+begin_src sh

   sudo apt-get install emacs

   #+end_src

   And the flavour that I --like-- liked most is the *spacemacs*
   https://www.spacemacs.org/

   The following lines will move your current personal folder from
   emacs to back-up (just in case), and then will clone the latest
   stable repository for espacemacs.

   #+begin_src sh

   mv ~/.emacs.d ~/.emacs.d.old
   git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

   #+end_src

   With version 25 (current version is 27 by the time of writing) of
   EMACS in Ubuntu 18 i found an issue, related to signature update,
   if you find yourself again with this error you can solve it
   following the instructions:

   You can check your linux version with the following code:

   #+begin_src sh

   uname -a

   #+end_src
   #+RESULTS:
   : Linux localhost.localdomain 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

   Documentation on "signature" fails after spacemacs install:

   - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

**** My stored spacemacs configuration

     Here is the most stable configuration on *.spacemacs* file inside
     the dotfiles folder.

     #+begin_src sh

     cp ~/.spacemacs ~/.spacemacs.bk
     cp ./dotfiles/spacemacs/.spacemacs ~/.spacemacs

     #+end_src

***** DONE Move spacemacs configuration to dotfile folder
      <2021-05-30 dom> Fixed. In fact I was using dotfile folder for
      storing .emacs


*** DOOM EMACS
    
    I'm trying new things, after getting bored of watching DOOM Emacs videos, I just tought... let's try it!

    Starting at: <2020-12-18 vie> ... we will see...


    #+begin_src sh

    git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install

    #+end_src

    After several months using it I found Doom Emacs too big for my use, I
    mainly use: ORG, HUGO and some few things, so I preferred to have more
    minimalistic configuration.

*** EMACS my own Config

    Finally I found myself wanted something less bloated, more
    light. May be I will lose some functionallities but at least I
    will configure the ones that I use.

    At this moment I'm just configuring .emacs file, not dotorg
    config, for now...

    #+begin_src sh
    
    mv -v ~/.emacs ~/.emacs.bk
    cp -v ./dotfiles/.emacs ~/.emacs

    #+end_src

    This config uses some "art" 

    #+begin_src sh

    cp -vr ./art ~/Imágenes/art 

    #+end_src

** GIMP

   The graphical editor!

   #+begin_src sh

   sudo apt-get install gimp

   #+end_src

* Terminal
** system
   This section is in which i recommend some system tools if not installed.
*** HTop                                                  :system:monitoring:

    Mostly (AFAIK) top should be included, but htop is more powerfull
    and fancy from terminal

    #+begin_src sh :results output

    sudo dnf install htop

    #+end_src

    #+RESULTS:

*** Bashtop                                               :system:monitoring:
    
    Very nice application to be installed, all the linux youtubers use
    it, so you should so, shouldn't? B)

    #+BEGIN_SRC sh
    
    sudo dnf install bashtop 
    
    #+END_SRC

** Powerline

   Powerline is a very usefull aplication when you use git, I
   recommend to install it. More info at:

   For ubuntu

   #+begin_src sh

   sudo apt-get install fonts-powerline powerline

   #+end_src

   For DNF package manager

   #+begin_src sh

   sudo dnf install powerline

   #+end_src

   #+RESULTS:

   After installation you should include into your .bashrc the
   initialization of the powerline, for doing this first check your
   installation path
   
   #+begin_src sh

   whereis powerline

   #+end_src
   #+RESULTS:
   : powerline: /usr/bin/powerline /usr/share/powerline /usr/share/man/man1/powerline.1.gz

   You should have a script to be included on your .bashrc: 

   #+begin_src sh

   ls -l /usr/share/powerline/bash/powerline.sh

   #+end_src
   #+RESULTS:
   : -rw-r--r--. 1 root root 4183 mar 15 10:31 /usr/share/powerline/bash/powerline.sh

   If th above is working then you can addit executing the following code:

   #+begin_src sh

   cp ~/.bashrc ~/.bashrc.bk
   echo "# Powerline" >> ~/.bashrc
   echo "export PATH=$PATH:$HOME/Library/Python/2.7/bin" >> ~/.bashrc
   echo "powerline-daemon -q" >> ~/.bashrc
   echo "POWERLINE_BASH_CONTINUATION=1" >>  ~/.bashrc
   echo "POWERLINE_BASH_SELECT=1" >> ~/.bashrc
   echo ". /usr/share/powerline/bash/powerline.sh" >> ~/.bashrc
   echo "Done! :)"

   #+end_src

   #+RESULTS:
   : Done! :)

   Check your Python version BTW

   #+begin_src sh :results output

   python -V

   #+end_src

   #+RESULTS:
   : Python 3.9.1

   Now you want to add to the powerline the git theme on Shell, this is very easy!
   I added in the repo my config file for this (very standard BTW).

   #+begin_src sh

   cp /usr/share/powerline/config_files/config.json ./config.json.bk
   cp ./powerline-conf/config.json /usr/share/powerline/config_files/

   #+end_src

   #+RESULTS:

   You will need to open a new terminal after changing the
   *config.json* file.

   More info: https://devpro.media/install-powerline-ubuntu/#edit-your-powerline-configuration

*** TODO To improve colors in powerline-git config to show changes on directory are pending

** Some fun
*** Pokemon on your terminal

   I love the pokemon say addon for terminal, is a litle bit of fun on
   your term:

   - https://github.com/possatti/pokemonsay

   #+begin_src sh

   sudo apt-get install fortune cowsay

   #+end_src

   For Fedora, there is an slight difference

   #+begin_src sh

   sudo dnf install fortune-mod
   sudo dnf install cowsay

   #+end_src

   #+RESULTS:

   Some test that you have preinstalled what is needed:

   #+begin_src sh :results output

   fortune | cowsay

   #+end_src

   #+RESULTS:
   :  ___________________________
   : < Life is not for everyone. >
   :  ---------------------------
   :         \   ^__^
   :          \  (oo)\_______
   :             (__)\       )\/\
   :                 ||----w |
   :                 ||     ||

   #+begin_src sh :results output

   cd ~/
   git clone http://github.com/possatti/pokemonsay
   cd pokemonsay
   ./install.sh

   #+end_src

   #+RESULTS:
   : The files were installed to '/home/danioche/.pokemonsay/'.
   : A 'pokemonsay' script was created in '/home/danioche/bin/'.
   : A uninstall script was created in '/home/danioche/.pokemonsay/'.
   : It may be necessary to logout and login back again in order to have the 'pokemonsay' available in your path.

   Now you want to add it to your .bashrc file to get some cool wellcome everytime you enter to your terminal.

   #+begin_src sh :results output

   cp ~/.bashrc ~/.bashrc.before.pokesay
   echo "# Pokemon say add-on" >> ~/.bashrc
   echo "fortune | ~/bin/pokemonsay " >> ~/.bashrc
   diff ~/.bashrc ~/.bashrc.before.pokesay

   #+end_src

   #+RESULTS:

*** Ascii art

    Sometimes is nice to beutify your terminal with some ascii art.

    #+begin_src sh
    
    sudo dnf install figlet
    
    #+end_src 

    #+RESULTS:

    You can test it!

    #+begin_src sh 

    fig hello

    #+end_src

    #+RESULTS:

** Fonts

   Source Code Pro is the default font for Emacs, and also is a nice font. Here is how to install it.

   #+begin_src sh :results output

   git clone https://github.com/adobe-fonts/source-code-pro.git ./source-code-pro
   mkdir ~/.fonts
   cp ./source-code-pro/OTF/*.otf ~/.fonts/
   fc-cache -f -v

   #+end_src

   #+RESULTS:
   #+begin_example
   Font directories:
	   /usr/share/fonts
	   /usr/share/X11/fonts/Type1
	   /usr/share/X11/fonts/TTF
	   /usr/local/share/fonts
	   /home/danioche/.local/share/fonts
	   /home/danioche/.fonts
	   /usr/share/fonts/aajohan-comfortaa
	   /usr/share/fonts/adobe-source-code-pro
	   /usr/share/fonts/cantarell
	   /usr/share/fonts/dejavu-sans-fonts
	   /usr/share/fonts/dejavu-sans-mono-fonts
	   /usr/share/fonts/dejavu-serif-fonts
	   /usr/share/fonts/gdouros-symbola
	   /usr/share/fonts/google-carlito-fonts
	   /usr/share/fonts/google-droid-sans-fonts
	   /usr/share/fonts/google-noto
	   /usr/share/fonts/google-noto-cjk
	   /usr/share/fonts/google-noto-emoji
	   /usr/share/fonts/google-noto-vf
	   /usr/share/fonts/ht-caladea-fonts
	   /usr/share/fonts/jomolhari-fonts
	   /usr/share/fonts/julietaula-montserrat
	   /usr/share/fonts/khmeros
	   /usr/share/fonts/liberation-mono
	   /usr/share/fonts/liberation-sans
	   /usr/share/fonts/liberation-serif
	   /usr/share/fonts/lohit-assamese
	   /usr/share/fonts/lohit-bengali
	   /usr/share/fonts/lohit-devanagari
	   /usr/share/fonts/lohit-gujarati
	   /usr/share/fonts/lohit-kannada
	   /usr/share/fonts/lohit-odia
	   /usr/share/fonts/lohit-tamil
	   /usr/share/fonts/lohit-telugu
	   /usr/share/fonts/opensymbol
	   /usr/share/fonts/paktype-naskh-basic
	   /usr/share/fonts/pt-sans-fonts
	   /usr/share/fonts/sil-abyssinica-fonts
	   /usr/share/fonts/sil-mingzat
	   /usr/share/fonts/sil-nuosu
	   /usr/share/fonts/sil-padauk
	   /usr/share/fonts/smc-meera
	   /usr/share/fonts/stix-fonts
	   /usr/share/fonts/thai-scalable
	   /usr/share/fonts/truetype
	   /usr/share/fonts/urw-base35
   /usr/share/fonts: caching, new cache contents: 0 fonts, 40 dirs
   /usr/share/fonts/aajohan-comfortaa: caching, new cache contents: 3 fonts, 0 dirs
   /usr/share/fonts/adobe-source-code-pro: caching, new cache contents: 14 fonts, 0 dirs
   /usr/share/fonts/cantarell: caching, new cache contents: 11 fonts, 0 dirs
   /usr/share/fonts/dejavu-sans-fonts: caching, new cache contents: 9 fonts, 0 dirs
   /usr/share/fonts/dejavu-sans-mono-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/dejavu-serif-fonts: caching, new cache contents: 9 fonts, 0 dirs
   /usr/share/fonts/gdouros-symbola: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/google-carlito-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/google-droid-sans-fonts: caching, new cache contents: 16 fonts, 0 dirs
   /usr/share/fonts/google-noto: caching, new cache contents: 2 fonts, 0 dirs
   /usr/share/fonts/google-noto-cjk: caching, new cache contents: 45 fonts, 0 dirs
   /usr/share/fonts/google-noto-emoji: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/google-noto-vf: caching, new cache contents: 72 fonts, 0 dirs
   /usr/share/fonts/ht-caladea-fonts: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/jomolhari-fonts: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/julietaula-montserrat: caching, new cache contents: 18 fonts, 0 dirs
   /usr/share/fonts/khmeros: caching, new cache contents: 3 fonts, 0 dirs
   /usr/share/fonts/liberation-mono: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/liberation-sans: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/liberation-serif: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/lohit-assamese: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-bengali: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-devanagari: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-gujarati: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-kannada: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-odia: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-tamil: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/lohit-telugu: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/opensymbol: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/paktype-naskh-basic: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/pt-sans-fonts: caching, new cache contents: 8 fonts, 0 dirs
   /usr/share/fonts/sil-abyssinica-fonts: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-mingzat: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-nuosu: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/sil-padauk: caching, new cache contents: 2 fonts, 0 dirs
   /usr/share/fonts/smc-meera: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/stix-fonts: caching, new cache contents: 5 fonts, 0 dirs
   /usr/share/fonts/thai-scalable: caching, new cache contents: 4 fonts, 0 dirs
   /usr/share/fonts/truetype: caching, new cache contents: 1 fonts, 0 dirs
   /usr/share/fonts/urw-base35: caching, new cache contents: 69 fonts, 0 dirs
   /usr/share/X11/fonts/Type1: skipping, no such directory
   /usr/share/X11/fonts/TTF: skipping, no such directory
   /usr/local/share/fonts: skipping, no such directory
   /home/danioche/.local/share/fonts: caching, new cache contents: 6 fonts, 0 dirs
   /home/danioche/.fonts: caching, new cache contents: 0 fonts, 0 dirs
   /usr/share/fonts/aajohan-comfortaa: skipping, looped directory detected
   /usr/share/fonts/adobe-source-code-pro: skipping, looped directory detected
   /usr/share/fonts/cantarell: skipping, looped directory detected
   /usr/share/fonts/dejavu-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/dejavu-sans-mono-fonts: skipping, looped directory detected
   /usr/share/fonts/dejavu-serif-fonts: skipping, looped directory detected
   /usr/share/fonts/gdouros-symbola: skipping, looped directory detected
   /usr/share/fonts/google-carlito-fonts: skipping, looped directory detected
   /usr/share/fonts/google-droid-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/google-noto: skipping, looped directory detected
   /usr/share/fonts/google-noto-cjk: skipping, looped directory detected
   /usr/share/fonts/google-noto-emoji: skipping, looped directory detected
   /usr/share/fonts/google-noto-vf: skipping, looped directory detected
   /usr/share/fonts/ht-caladea-fonts: skipping, looped directory detected
   /usr/share/fonts/jomolhari-fonts: skipping, looped directory detected
   /usr/share/fonts/julietaula-montserrat: skipping, looped directory detected
   /usr/share/fonts/khmeros: skipping, looped directory detected
   /usr/share/fonts/liberation-mono: skipping, looped directory detected
   /usr/share/fonts/liberation-sans: skipping, looped directory detected
   /usr/share/fonts/liberation-serif: skipping, looped directory detected
   /usr/share/fonts/lohit-assamese: skipping, looped directory detected
   /usr/share/fonts/lohit-bengali: skipping, looped directory detected
   /usr/share/fonts/lohit-devanagari: skipping, looped directory detected
   /usr/share/fonts/lohit-gujarati: skipping, looped directory detected
   /usr/share/fonts/lohit-kannada: skipping, looped directory detected
   /usr/share/fonts/lohit-odia: skipping, looped directory detected
   /usr/share/fonts/lohit-tamil: skipping, looped directory detected
   /usr/share/fonts/lohit-telugu: skipping, looped directory detected
   /usr/share/fonts/opensymbol: skipping, looped directory detected
   /usr/share/fonts/paktype-naskh-basic: skipping, looped directory detected
   /usr/share/fonts/pt-sans-fonts: skipping, looped directory detected
   /usr/share/fonts/sil-abyssinica-fonts: skipping, looped directory detected
   /usr/share/fonts/sil-mingzat: skipping, looped directory detected
   /usr/share/fonts/sil-nuosu: skipping, looped directory detected
   /usr/share/fonts/sil-padauk: skipping, looped directory detected
   /usr/share/fonts/smc-meera: skipping, looped directory detected
   /usr/share/fonts/stix-fonts: skipping, looped directory detected
   /usr/share/fonts/thai-scalable: skipping, looped directory detected
   /usr/share/fonts/truetype: skipping, looped directory detected
   /usr/share/fonts/urw-base35: skipping, looped directory detected
   /usr/lib/fontconfig/cache: not cleaning unwritable cache directory
   /home/danioche/.cache/fontconfig: cleaning cache directory
   /home/danioche/.fontconfig: not cleaning non-existent cache directory
   /usr/bin/fc-cache-64: succeeded
   #+end_example
   
* Productivity
** Code snipets

   This is very useful, you can use skeleton (code in lisp) or you can
   use a module called *yasnippet*, well documented here:

   - https://jaketrent.com/post/code-snippets-spacemacs/ 

   For seleton you can use a configuration layer in spacemacs and code
   your own skeleton in elisp, I made this way some skeleton for IPM
   porpuses.

** Music
*** Lazy Option: Spotify

    Spotify, it's a crap. I'm looking for replacement, but for now...

    #+begin_src sh

    snap install spotify

    #+end_src

** Presentations
*** reveal-js for Spaceemacs configuration

    A part from LibreOffice suite you may want to have a powerfull tool for presentation. 
    This is for sure reveal.js, you can include it in your org configuration adding in your user layer */dotspacemacs-configuration-layers/*  inside */dotspacemacs/layers/* the following

    #+begin_src lisp
     org
     (org :variables
          org-enable-github-support t
          org-enable-reveal-js-support t)
    #+end_src 

    This configuration is included in the *.spacemacs* file. 

* Blogging

  In this section I will document the use of Hugo and how I adopted
  org-mode with Hugo static web generation.

  Firts of all we need to install Hugo, in Fedora

  #+begin_src sh

  sudo dnf install hugo

  #+end_src

  This is the template that I used as the base for my new blog:
  Anatole Template https://themes.gohugo.io/anatole/

  Adding the template to the current project
  
  I documented the process of the installation and configuration using
  Hugo as static generation in combination with Org-mode.

  Find the post here:
  - https://danioche.github.io/blog

* Destkop Customization
** GDM - Fedora login screen background

   This should be easy but isn't... something quite simple like
   changing the user's login background it is a little big triky.

   For being able to modify the Gnome Desktop Manager login screen
   background you will need to download an specific application.

   Here is what I found in
   https://copr.fedorainfracloud.org/coprs/zirix/gdm-wallpaper/

   #+begin_src sh

   sudo dnf copr enable zirix/gdm-wallpaper
   sudo dnf install gdm-wallpaper
   sudo set-gdm-wallpaper /path/to/image.png

   #+end_src

   And works! I disabled the repository added just in case once is
   installed.

** i3 tiling windows manager

   I'm just trying this, for me is good to have more focus on the
   work, avoiding disrruption and because of this I'm trying i3.

   I tricked some battery problems with the i3status bar, there is a
   .conf file in this repo that you can use:

   #+begin_src sh

   cp ./i3/.i3status.conf ~/

   #+end_src

   Documentation can be found here:
   https://i3wm.org/docs/userguide.html#_default_keybindings

   #+begin_example sh

   ln -s /sys/class/power_supply/axp288_fuel_gauge/ BAT1

   #+end_example

** xmonad tiling windows manager

   I've tried Xmonad and has that minimilistic touch that I love, so
   this is an option to take into consideration, heres is how to
   install.

   The following is for install For Fedora:

   #+begin_src sh

   sudo dnf install xmonad

   #+end_src

   I use xmobar with xmonad, so let's install it:

   #+begin_src sh

   sudo dnf install xmobar

   #+end_src

   For easy the configuration you have .xmonad and .xmobarrc inside
   *dotfiles*

   #+begin_src sh :results output

     printf "Check config and other scripts used by Xmonad and Xmobar:\n\n"
     ls -l dotfiles/.xmo*

   #+end_src

   #+RESULTS:
   #+begin_example
   Check config and other scripts used by Xmonad and Xmobar:

   -rw-r--r--. 1 danioche danioche 1863 ene 24 10:18 dotfiles/.xmobarrc

   dotfiles/.xmonad:
   total 5384
   -rwxrwxrwx. 1 danioche danioche     793 ene  1 19:15 get-Battery.sh
   -rwxrwxrwx. 1 danioche danioche     267 dic 26 21:07 get-Volume.sh
   -rwxrwxrwx. 1 danioche danioche    1245 ene  4 19:20 get-Weather.sh
   -rwxrwxrwx. 1 danioche danioche   30255 dic 27 20:45 icons.all
   -rwxrwxrwx. 1 danioche danioche     318 ene 23 19:13 set-Brightness.sh
   -rwxrwxrwx. 1 danioche danioche     345 ene  6 18:59 weather-status.info
   -rwxrwxrwx. 1 danioche danioche     560 ene  9 11:49 xmonad.errors
   -rwxrwxrwx. 1 danioche danioche    3834 ene  8 19:38 xmonad.hi
   -rwxrwxrwx. 1 danioche danioche   12405 ene 23 19:13 xmonad.hs
   -rw-r--r--. 1 danioche danioche   76568 ene  9 11:49 xmonad.o
   -rwxr-xr-x. 1 danioche danioche 5357008 ene  9 11:49 xmonad-x86_64-linux
   #+end_example

   Here is the configuration for xmobar

   #+begin_src sh :results output

     cat dotfiles/.xmobarrc

   #+end_src

   #+RESULTS:
   #+begin_example
   Config { font = "xft:DejaVu Sans Mono:size=10,Font Awesome:size=9"
	  , bgColor = "black"
	  , fgColor = "grey"
	  , position = Top
	  , lowerOnStart = True
	  , commands = [ Run Network "wlp1s0" ["-L","0","-H","15000","--normal","green","--high","red","-S","True","--template","<fc=#04d9ff></fc> <rx>|<tx>"] 10
		       , Run MultiCpu ["-L","3","-H","50","--normal","green","--high","red","-t","<fc=#04d9ff></fc> <bar>"] 10
		       , Run Memory ["-t","<fc=#04d9ff></fc> <usedratio>%"] 10
		       , Run Swap ["-t", "<fc=#04d9ff>S</fc> <usedratio>%"] 10
		       , Run Com "/home/danioche/.xmonad/get-Battery.sh" [] "myBatt" 60
		       , Run WeatherX "LEAL"
			     [ ("clear", "🌣")
			     , ("sunny", "🌣")
			     , ("mostly clear", "🌤")
			     , ("mostly sunny", "🌤")
			     , ("partly sunny", "⛅")
			     , ("fair", "🌑")
			     , ("cloudy","☁")
			     , ("overcast","☁")
			     , ("partly cloudy", "⛅")
			     , ("mostly cloudy", "🌧")
			     , ("considerable cloudiness", "⛈")]
			     ["-t", "<fc=#04d9ff>W</fc> <fn=2><skyConditionS></fn> <tempC>º  <rh>%   <windCardinal>(<windAzimuth>º)  <windKnots>"
			     , "-L","10", "-H", "25", "--normal", "black"
			     , "--high", "lightgoldenrod4", "--low", "darkseagreen4"] 18000
		       , Run Date "%a %b %_d %Y %H:%M:%S" "date" 10
		       ]
	  , sepChar = "%"
	  , alignSep = "}{"
	  , template = "%multicpu% | %memory% %swap% | %wlp1s0% }<fc=#ee9a00> %date%</fc>{ %LEAL% | %myBatt%"
   }
   #+end_example
