#+TITLE: Danioche linux set-up
#+AUTHOR: @danioche
#+DATE: <2020-05-25 lun>
#+MODIFIED: <2020-06-07 dom>

* About
  
This document should be used to help to configure *any* Ubuntu distro to working-distro with the most common set-up that I'm used to. 
Main tools, corporate and productivity tools, and of course look&feel from a preconfigured repo.

Following literate documentation approach, inspiring post: http://cachestocaches.com/2018/6/org-literate-programming/ 


#+ATTR_TEXTINFO: :author @danioche
#+BEGIN_QUOTE

All the shell code here comes without any warranty, execute it (or not) at your own risk.
I assume that you understand the code, you can modify it, as always, at your own risk.

#+END_QUOTE

Bellow the latest commit mesage:

#+begin_src sh

git log -1 --pretty=%B

#+end_src
#+RESULTS:
: Creation of first contents and check on code blocks

** Check your space

You may want to check your disk space befor continue on this customization:

#+begin_src sh

df -H

#+end_src

#+RESULTS:
| S.ficheros     | Tamaño | Usados | Disp | Uso% | Montado                       | en |
| udev           | 947M   | 0      | 947M |   0% | /dev                          |    |
| tmpfs          | 197M   | 1      | 195M |   1% | /run                          |    |
| /dev/mmcblk0p2 | 31G    | 12G    |  18G |  40% | /                             |    |
| tmpfs          | 983M   | 123M   | 861M |  13% | /dev/shm                      |    |
| tmpfs          | 5      | 4      |    5 |   1% | /run/lock                     |    |
| tmpfs          | 983M   | 0      | 983M |   0% | /sys/fs/cgroup                |    |
| /dev/loop1     | 132k   | 132k   |    0 | 100% | /snap/software-boutique/54    |    |
| /dev/loop0     | 437M   | 437M   |    0 | 100% | /snap/libreoffice/180         |    |
| /dev/loop2     | 169M   | 169M   |    0 | 100% | /snap/gnome-3-28-1804/116     |    |
| /dev/loop3     | 437M   | 437M   |    0 | 100% | /snap/libreoffice/179         |    |
| /dev/loop4     | 99M    | 99M    |    0 | 100% | /snap/core/9066               |    |
| /dev/loop5     | 8      | 8      |    0 | 100% | /snap/pulsemixer/250          |    |
| /dev/loop6     | 16M    | 16M    |    0 | 100% | /snap/ubuntu-mate-welcome/539 |    |
| /dev/loop7     | 16M    | 16M    |    0 | 100% | /snap/ubuntu-mate-welcome/420 |    |
| /dev/loop8     | 94M    | 94M    |    0 | 100% | /snap/core/8268               |    |
| /dev/loop9     | 66M    | 66M    |    0 | 100% | /snap/gtk-common-themes/1506  |    |
| /dev/loop10    | 8      | 8      |    0 | 100% | /snap/pulsemixer/283          |    |
| /dev/loop11    | 132k   | 132k   |    0 | 100% | /snap/software-boutique/39    |    |
| /dev/loop13    | #+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js58M    | 58M    |    0 | 100% | /snap/core18/1754             |    |
| /dev/mmcblk0p1 | 536M   | 6      | 530M |   2% | /boot/efi                     |    |
| tmpfs          | 197M   | 3      | 193M |   2% | /run/user/1000                |    |
| /dev/loop12    | 172M   | 172M   |    0 | 100% | /snap/spotify/41              |    |

** Improvements

Some TODOs for the future

*** TODO Backup section
*** TODO Auto-install scripts

* This repo

The structure that I want is a private repository that will have all the scripts needed to config the new distro.
Obviously what is inside is this main ORG file, that is a literate document; so once you installed Emacs and Spacemacs you will be able to execute the configurations as you wish.

Summarizing, the step-0 is to have git.

#+begin_src sh

git version

#+end_src
#+RESULTS:
: git version 2.17.1

If Ctr+C Ctr+C does not works showing you the following message: "Evaluation of this sh code block is disabled" then you may have a problem on configuration here is a trick:

 - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

** Installing git

The following command may be not fully working from this documentation, but you can copy-paste to install it.

#+begin_src sh

sudo apt-get install git

#+end_src
#+RESULTS:

If your Linux is brand new you may need to add your .rsa or create a new one for the nes OS, follow the instructions here:

 - https://github.com/settings/keys

 - Help info: 
   - https://help.github.com/articles/generating-a-gpg-key/

/*Obviously*: If you don't have emacs installed and configured you will not be able to execute here the code above, so you may want to visit next section./

* Tools
** Main tool EMACS, *spacemacs* flavored

The main tool (a part from git :) for taking the most of this document is EMACS, you want to have it installed.

 - https://www.gnu.org/software/emacs/

I'm using EMACS since 2017 for Instant Project Management, TimeSheet management, GTD and other cool stuff like to support this document.
which is mostly the key for many features and tricks that I'm doing in my everyday work stream.

#+begin_src sh

sudo apt-get install emacs

#+end_src

And the flavour that I like most is the *spacemacs* https://www.spacemacs.org/

The following lines will move your current personal folder from emacs to back-up (just in case), and then will clone the latest stable repository for espacemacs.

#+begin_src sh

mv ~/.emacs.d ~/.emacs.d.old
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

#+end_src

With version 25 of EMACS in Ubuntu 18 i found an issue, related to signature update, if you find yourself again with this error you can solve it following the instructions:

You can check your linux version with the following code:

#+begin_src sh

uname -a

#+end_src
#+RESULTS:
: Linux Pavilion 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Documentation on "signature" fails after spacemacs install:

 - https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

*** I want my config back!

Here is the most stable configuration on *.spacemacs* file.

#+begin_src sh 

cp ~/.spacemacs ~/.spacemacs.bk
cp ./spacemacs/.spacemacs ~/.spacemacs

#+end_src

* Terminal
** Powerline
 
Powerline is a very usefull aplication when you use git, I recommend to install it. More info at: 

#+begin_src sh

sudo apt-get install fonts-powerline powerline

#+end_src

After installation you should include into your .bashrc the initialization of the powerline, for doing this first check your installation path

#+begin_src sh

whereis powerline

#+end_src
#+RESULTS:
: powerline: /usr/bin/powerline /usr/share/powerline /usr/share/man/man1/powerline.1.gz

You should have a script to be included on your .bashrc: 

#+begin_src sh

ls -l /usr/share/powerline/bindings/bash/powerline.sh 

#+end_src
#+RESULTS:
: -rw-r--r-- 1 root root 3042 may  8  2017 /usr/share/powerline/bindings/bash/powerline.sh

If th above is working then you can addit executing the following code:

#+begin_src sh

cp ~/.bashrc ~/.bashrc.bk
echo "\n\n# Powerline" >> ~/.bashrc
echo "\nexport PATH=$PATH:$HOME/Library/Python/2.7/bin" >> ~/.bashrc
echo "\npowerline-daemon -q" >> ~/.bashrc
echo "\nPOWERLINE_BASH_CONTINUATION=1" >>  ~/.bashrc
echo "\nPOWERLINE_BASH_SELECT=1" >> ~/.bashrc
echo "\n. /usr/share/powerline/bindings/bash/powerline.sh" >> ~/.bashrc
echo "Done! :)"

#+end_src

#+RESULTS:
: Done! :)

Check your Python version BTW

#+begin_src sh :results output

python -V

#+end_src

#+RESULTS:

Now you want to add to the powerline the git theme on Shell, this is very easy!
I added in the repo my config file for this (very standard BTW).

#+begin_src sh

cp /usr/share/powerline/config_files/config.json ./config.json.bk
cp ./powerline-conf/config.json /usr/share/powerline/config_files/

#+end_src

You will need to open a new terminal after changing the *config.json* file.

More info: https://devpro.media/install-powerline-ubuntu/#edit-your-powerline-configuration

*** TODO To improve colors in powerline-git config to show changes on directory are pending

** Some fun

I love the pokemon say addon for terminal, is a litle bit of fun on your term:

 - https://github.com/possatti/pokemonsay

#+begin_src sh

sudo apt-get install fortune cowsay

#+end_src

#+RESULTS:

Some test that you have preinstalled what is needed:

#+begin_src sh :results output

fortune | cowsay

#+end_src

#+RESULTS:
:  ______________________________________
: / You have an unusual equipment for    \
: \ success. Be sure to use it properly. /
:  --------------------------------------
:         \   ^__^
:          \  (oo)\_______
:             (__)\       )\/\
:                 ||----w |
:                 ||     ||

#+begin_src sh :results output

cd ~/
git clone http://github.com/possatti/pokemonsay
cd pokemonsay
./install.sh

#+end_src

#+RESULTS:
: The files were installed to '/home/ebh/.pokemonsay/'.
: A 'pokemonsay' script was created in '/home/ebh/bin/'.
: A uninstall script was created in '/home/ebh/.pokemonsay/'.
: It may be necessary to logout and login back again in order to have the 'pokemonsay' available in your path.

Now you want to add it to your .bashrc file to get some cool wellcome everytime you enter to your terminal.

#+begin_src sh :results output

cp ~/.bashrc ~/.bashrc.before.pokesay
echo "\n\n# Pokemon say add-on\n fortune | ./bin/pokemonsay " >> ~/.bashrc
diff ~/.bashrc ~/.bashrc.before.pokesay

#+end_src

#+RESULTS:

** Fonts

Source Code Pro is the default font for Emacs, and also is a nice font. Here is how to install it.

#+begin_src sh :results output

git clone https://github.com/adobe-fonts/source-code-pro.git ./source-code-pro
mkdir ~/.fonts
cp ./source-code-pro/OTF/*.otf ~/.fonts/
fc-cache -f -v

#+end_src

#+RESULTS:
#+begin_example
/usr/share/fonts: caching, new cache contents: 0 fonts, 7 dirs
/usr/share/fonts/X11: caching, new cache contents: 0 fonts, 4 dirs
/usr/share/fonts/X11/Type1: caching, new cache contents: 8 fonts, 0 dirs
/usr/share/fonts/X11/encodings: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/X11/encodings/large: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/X11/misc: caching, new cache contents: 125 fonts, 0 dirs
/usr/share/fonts/X11/util: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cMap: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap: caching, new cache contents: 0 fonts, 5 dirs
/usr/share/fonts/cmap/adobe-cns1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-gb1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-japan1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-japan2: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-korea1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/opentype: caching, new cache contents: 1 fonts, 4 dirs
/usr/share/fonts/opentype/malayalam: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/opentype/mathjax: caching, new cache contents: 24 fonts, 0 dirs
/usr/share/fonts/opentype/noto: caching, new cache contents: 28 fonts, 0 dirs
/usr/share/fonts/opentype/opendyslexic: caching, new cache contents: 9 fonts, 0 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 44 dirs
/usr/share/fonts/truetype/Gargi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Gubbi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Nakula: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Navilu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Sahadeva: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Sarai: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/abyssinica: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/dejavu: caching, new cache contents: 22 fonts, 0 dirs
/usr/share/fonts/truetype/droid: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-beng-extra: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-deva-extra: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-gujr-extra: caching, new cache contents: 5 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-guru-extra: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-kalapi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-orya-extra: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-telu-extra: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-tiresias: caching, new cache contents: 22 fonts, 0 dirs
/usr/share/fonts/truetype/freefont: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/truetype/kacst: caching, new cache contents: 15 fonts, 0 dirs
/usr/share/fonts/truetype/kacst-one: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/lao: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-assamese: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-bengali: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-devanagari: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-gujarati: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-kannada: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-malayalam: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-oriya: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-punjabi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-tamil: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-tamil-classical: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-telugu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/malayalam: caching, new cache contents: 11 fonts, 0 dirs
/usr/share/fonts/truetype/noto: caching, new cache contents: 206 fonts, 0 dirs
/usr/share/fonts/truetype/padauk: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/truetype/pagul: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/samyak: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/samyak-fonts: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/truetype/sinhala: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/tibetan-machine: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/tlwg: caching, new cache contents: 58 fonts, 0 dirs
/usr/share/fonts/truetype/ttf-khmeros-core: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/ubuntu: caching, new cache contents: 13 fonts, 0 dirs
/usr/share/fonts/type1: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/type1/gsfonts: caching, new cache contents: 35 fonts, 0 dirs
/usr/share/fonts/woff: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/woff/opendyslexic: caching, new cache contents: 4 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/home/ebh/.local/share/fonts: skipping, no such directory
/home/ebh/.fonts: caching, new cache contents: 14 fonts, 0 dirs
/var/cache/fontconfig: not cleaning unwritable cache directory
/home/ebh/.cache/fontconfig: cleaning cache directory
/home/ebh/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
#+end_example

* Productivity
** Code snipets

This is very useful, you can use skeleton (code in lisp) or you can use a module called *yasnippet*, well documented here:

 - https://jaketrent.com/post/code-snippets-spacemacs/ 

For seleton you can use a configuration layer in spacemacs and code your own skeleton in elisp, I made this way some skeleton for IPM porpuses.

** Music

Spotify, it's a crap. I'm looking for replacement, but for now...

#+begin_src sh

snap install spotify

#+end_src

#+RESULTS:

** Presentations

A part from LibreOffice suite you may want to have a powerfull tool for presentation. 
This is for sure reveal.js, you can include it in your org configuration adding in your user layer */dotspacemacs-configuration-layers/*  inside */dotspacemacs/layers/* the following

#+begin_src lisp
     org
     (org :variables
          org-enable-github-support t
          org-enable-reveal-js-support t)
#+end_src 

This configuration is included in the *.spacemacs* file. 

* Destkop
** i3 tiling windows manager

I'm just trying this, for me is good to have more focus on the work, avoiding disrruption and because of this I'm trying i3.

I tricked some battery problems with the i3status bar, there is a .conf file in this repo that you can use:

#+begin_src sh

cp ./i3/.i3status.conf ~/

#+end_src

* Tools
** GIMP
The graphical editor!

#+begin_src sh

sudo apt-get install gimp

#+end_src



